eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}
service:
    name: payment-service
spring:
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        password: deepak
        platform: postgres
        testWhileIdle: true
        url: jdbc:postgresql://localhost:5432/postgres
        username: paymentdb
        validationQuery: SELECT 1
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: localhost:9092
            group-id: group-id
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
zipkin:
    baseUrl: http://localhost:9411