version: "3.9"

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  db:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: deepak

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  broker:
    image: apache/kafka:latest
    container_name: broker
#    ports:
#      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
#  config-server:
#    image: config-server
#    ports:
#      - 8888:8888
#    depends_on:
#      - zipkin

#  eureka-server:
#    image: eureka-server
#    ports:
#      - 8761:8761
#    depends_on:
#      - zipkin
#      - config-server

volumes:
  pgdata:

